# Generated by Django 4.2.4 on 2023-08-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaplecze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('ftp_user', models.CharField(max_length=64)),
                ('ftp_pass', models.CharField(max_length=64)),
                ('db_user', models.CharField(max_length=64)),
                ('db_pass', models.CharField(max_length=64)),
                ('lang', models.CharField(max_length=4)),
                ('topic', models.CharField(max_length=32)),
                ('wp_user', models.CharField(max_length=32)),
                ('wp_api_key', models.CharField(max_length=128)),
            ],
        ),
    ]
