# Generated by Django 4.2.4 on 2023-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaplecze',
            name='login',
            field=models.CharField(default='admin', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='password',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='url',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
