# Generated by Django 4.2.4 on 2023-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_zaplecze_login_zaplecze_password_zaplecze_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaplecze',
            name='db_pass',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='db_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='domain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='ftp_pass',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='ftp_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='lang',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='login',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='topic',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='wp_api_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='wp_user',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
