# Generated by Django 4.2.4 on 2023-08-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_zaplecze_db_pass_alter_zaplecze_db_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaplecze',
            name='wp_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
