# Generated by Django 4.2.4 on 2023-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_zaplecze_wp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaplecze',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
