# Generated by Django 4.2.4 on 2023-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='topic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
