# Generated by Django 4.2.4 on 2023-11-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
