# Generated by Django 4.2.4 on 2023-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_link_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='ul_id',
            field=models.CharField(default='client0', max_length=32),
        ),
    ]
