# Generated by Django 4.2.4 on 2023-12-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_link_ul_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='semstorm_api_key',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
