# Generated by Django 4.2.4 on 2024-01-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_zaplecze_wp_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cursor_followed',
            field=models.BooleanField(default=False),
        ),
    ]
