# Generated by Django 4.2.4 on 2024-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_account_cursor_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#add8e6', max_length=32)),
            ],
        ),
    ]
