# Generated by Django 4.2.4 on 2024-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
