# Generated by Django 4.2.4 on 2024-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_account_premium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='usd',
            field=models.FloatField(default=0.0),
        ),
    ]
