# Generated by Django 4.2.4 on 2024-01-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_account_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usd',
            new_name='USD',
        ),
    ]
