# Generated by Django 4.2.4 on 2024-02-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_usd_account_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapleczeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_creation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_registrar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_servername',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='domain_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='linked_websites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='outgoing_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='semstorm_top10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='semstorm_top10prev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='semstorm_top50',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='semstorm_top50prev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='ssl_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='ssl_expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='wp_category_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='wp_last_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaplecze',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.zapleczecategory'),
        ),
    ]
