# Generated by Django 4.2.4 on 2024-02-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_zapleczecategory_zaplecze_domain_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaplecze',
            name='domain_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='domain_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='ssl_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaplecze',
            name='ssl_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
