# Generated by Django 4.2.4 on 2024-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_zaplecze_domain_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zaplecza_shady',
            field=models.BooleanField(default=False),
        ),
    ]
