# Generated by Django 4.2.4 on 2024-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_account_zaplecza_shady'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeneoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
