# Generated by Django 4.2.4 on 2024-03-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_ceneofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceneofiles',
            old_name='fileName',
            new_name='name',
        ),
    ]
