# Generated by Django 4.2.4 on 2024-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_filename_ceneofiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pixabay_api_key',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
