# Generated by Django 4.2.4 on 2024-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_account_pixabay_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='vdTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_domain', models.CharField(max_length=256, unique=True)),
                ('server_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
