# Generated by Django 4.2.4 on 2024-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_primislaodomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primislaodomains',
            name='server_name',
            field=models.CharField(max_length=256),
        ),
    ]
