# Generated by Django 4.2.4 on 2024-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_primislaolinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='primislaolinks',
            name='link_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
