# Generated by Django 4.2.4 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_primislaolinks_link_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='primislaolinks',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
