# Generated by Django 4.2.4 on 2024-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_primislaolinks_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='primislaodomains',
            name='domain_category',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
